# Generated by Django 5.0.4 on 2024-05-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='area',
            new_name='size',
        ),
    ]
