# Generated by Django 5.0.4 on 2024-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_rename_area_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=255),
        ),
    ]
